### ISSUE TITLE
Session crashes when arguments are used in graph2ppt()

### ISSUE THREAD

**Issue by Kabouik** [tomwenseleers/export#1]
Hi,

I installed this package a few days ago and experienced a lot of R crashes trying to use it, both in R only and RStudio, as well as both on Linux Mint 17 x64 and Windows 7 x64.

I initially had trouble pinpointing what was exactly causing the issue, as the crash log first reported an issue with Java and core dump on my Linux machine. But after fixing this issue and many additional attempts, I noticed that the PPT export was working as long as I was using just the commandline `graph2ppt()`, and not something like `graph2office(type="PPT", "Blah blah blah.ppt")` or `graph2ppt("Blah blah blah.ppt")`. Same with `pptx` as an extension. I experienced the crashes even with simple filenames without special characters or spaces. The only way I could get the command not to crash the session was by setting no argument in the brackets.

I can observe this behaviour with any type of graph on both my Windows and Linux machines, so the following basic code should allow reproducing the crash:

```
hist(rnorm(1000))
graph2ppt("test.ppt")
```

I'm using R 3.2.2 and latest version of RStudio.

This package is very useful and I'm very happy that I could finally use it, thanks a lot for your work, and hope you'll find a way to fix this bug.

**Comment by tomwenseleers** [comment]
I think the problem is just that you need to explicitly name your arguments, as the first argument is otherwise assumed to be say a ggplot2 plot object. I think graph2ppt(file="test.ppt") should work! Also just updated the package and fixed some bugs so have a try!
