### ISSUE TITLE
Error in xpath_search(x$node, x$doc, xpath = xpath, nsMap = ns, num_results = 1) :    Memory allocation failed : growing nodeset hit limit

### ISSUE THREAD

**Issue by ArongYang** [tomwenseleers/export#17]
Hi，
I get an error when using graph2ppt():

Error in xpath_search(x$node, x$doc, xpath = xpath, nsMap = ns, num_results = 1) : 
  Memory allocation failed : growing nodeset hit limit
 [2]
Calls: graph2ppt ... xml_find_first -> xml_find_first.xml_node -> xpath_search -> .Call

And I get some information from https://stackoverflow.com/questions/40159864/getting-memory-allocation-failed-growing-nodeset-hit-limit-with-xml2-package. Unfortunately，I don't solve this problem. I will pleasure if you can give advice.

**Comment by tomwenseleers** [comment]
Would you happen to have a full reproducible example that produces this error? Otherwise it's a little difficult to figure out what might have gone wrong here...

**Comment by cvanderaa** [comment]
Could you give more information about what you try to export to ppt? It might be you are exporting a graph that is too heavy. What is the size of the data you are plotting?
