### ISSUE TITLE
Will graph2ppt support multiple plots exporting to powerpoint in the future?

### ISSUE THREAD

**Issue by ZWanBing** [tomwenseleers/export#18]
Hi!Thank you so much for writing this amazing package.
Is it possible that graph2ppt will support multiple plots exporting to powerpoint in the future?

**Comment by tomwenseleers** [comment]
You can do this with graph2ppt using the append=TRUE option, right? In that case all the plots will be appended as extra slides in your PPT. Or do you mean exporting multiple plots on one slide? In that case you have to arrange your plots first on one page before exporting (using mfrow(...) for base R plots or grid.arrange for ggplot2 plots).
