### ISSUE TITLE
ppt I export graph to gets corrupted

### ISSUE THREAD

**Issue by hwaterhouse** [tomwenseleers/export#19]
Hello,
I've been using your graph2ppt() function which was working beautifully appending graphs I made to an existing ppt I had. Suddenly I got this error:

graph2ppt(, file="/Users/hwaterhouse/Google Drive (hwaterhouse@ucdavis.edu)/PhD/Modesto/Manuscript 2nd chapter/Figures.pptx", append=TRUE)
Error in zip::unzip(zipfile = file, exdir = folder) : 
  zip error: `Cannot extract entry `ppt/media/image14.emf` from archive `/Users/hwaterhouse/Google Drive (hwaterhouse@ucdavis.edu)/PhD/Modesto/Manuscript 2nd chapter/Figures.pptx`` in file `zip.c:305`

It seems to think the ppt is zipped which it isn't... and now when I open my ppt other graphs I had in there from before using this function do not display (just a box with a red x in place of the picture of the graph). Any help would be greatly appreciated.

Thanks,
Hannah

**Comment by tomwenseleers** [comment]
Do you have a full reproducible example that reproduces this error by any chance? Perhaps the problem is linked to you wanted to add graphs to another powerpoint that was not originally made with the export package (which I never tested if that works or not)?

**Comment by hwaterhouse** [comment]
Hi Tom,
I think that was it- I was adding it to a power point that had not been made with the export package. The issue does not arise if you don’t use one that was already made.

Thank you,
Hannah
