### ISSUE TITLE
Error in graph2ppt()

### ISSUE THREAD

**Issue by noatrs** [tomwenseleers/export#2]
Hi,

I enjoy the export package very much. However recently, I started getting the following error:
Exported graph as ggplot_attempt_distribution_beakin.pptx
Warning message:
argument fontname is deprecated; please usefontname_serif, fontname_sans ,fontname_mono,fontname_symbol instead. 

> Do you have any idea what can be the problem? and how can I fix this?

Thanks in advance,

Noa

**Comment by tomwenseleers** [comment]
Just updated the code - this issue should be fixed now. Thanks for letting me know!
