### ISSUE TITLE
error: 'ph_with_vg_at' is defunct... when I tried to export a ggplot object to .pptx

### ISSUE THREAD

**Issue by liaojiahui-r** [tomwenseleers/export#23]
Hi!

error: 'ph_with_vg_at' is defunct.
Use 'officer::ph_with' instead.
See help("Defunct")

how to solve this problem? thx

**Comment by liaojiahui-r** [comment]
and... R version 3.6.2

**Comment by dockerytong** [comment]
this problem also happen to me when update to R 3.6.2 🤣

**Comment by llengcn** [comment]
Yes, dear export developer, I also met this problem after I installed some other packages (ggtree).  Since I use export every day, I tried to install export in another computer. The R version in that computer is 3.6.2 and I still met this problem. Could you please solve this problem? Thank you very much!

**Comment by Reewturge** [comment]
Hello!

To avoid this error tou need to install rvg package with old 2.1 version using CRAN.

**Comment by llengcn** [comment]
> Hello!
> 
> To avoid this error you need to install rvg package with old 2.1 version using CRAN.

Thank you very much!

**Comment by Biofarmer** [comment]
Hello!
May I ask how to solve the problem "object ‘location_eval’ is not exported by 'namespace:officer'"? The version of rvg is 2.1 and officer is 3.6. 
Thank you very much.

**Comment by realreal2020** [comment]
> > Hello!
> > To avoid this error you need to install rvg package with old 2.1 version using CRAN.
> 
> Thank you very much!

sorry, install old rvg did not work.
Any methods? Thanks!

**Comment by Yuxin-Cui** [comment]
I have also tried to install an old rvg, but found it can not be installed in R 3.6.3. Can anyone provide a practical guide?

**Comment by liaojiahui-r** [comment]
> I have also tried to install an old rvg, but found it can not be installed in R 3.6.3. Can anyone provide a practical guide?

Hello, I've installed rvg (2.1) succesfully under R version 3.6.3 and now export works well

> R version 3.6.3 (2020-02-29)
> Platform: x86_64-apple-darwin15.6.0 (64-bit)
> Running under: macOS Catalina 10.15.3 

I used these codes

`packageurl <- "https://cran.r-project.org/src/contrib/Archive/rvg/rvg_0.2.1.tar.gz"
install.packages(packageurl, repos = NULL, type = "source")`

<img width="1292" alt="截屏2020-03-2507 57 51" src="https://user-images.githubusercontent.com/61280250/77487864-88df1280-6e6e-11ea-82db-1fe90769ae41.png">

**Comment by Yuxin-Cui** [comment]
Thanks for your suggestion. I have tried it, but got an error message as follows:
** R
** inst
** byte-compile and prepare package for lazy loading
Error: package 'Rcpp' does not have a namespace
Execution halted
ERROR: lazy loading failed for package 'rvg'

**Comment by realreal2020** [comment]
> > I have also tried to install an old rvg, but found it can not be installed in R 3.6.3. Can anyone provide a practical guide?
> 
> Hello, I've installed rvg (2.1) successfully under R version 3.6.3 and now export works well
> 
> > R version 3.6.3 (2020-02-29)
> > Platform: x86_64-apple-darwin15.6.0 (64-bit)
> > Running under: macOS Catalina 10.15.3
> 
> I used these codes
> 
> > packageurl <- "https://cran.r-project.org/src/contrib/Archive/rvg/rvg_0.2.1.tar.gz"
> > install.packages(packageurl, repos = NULL, type = "source")
> 
> <img alt="截屏2020-03-2507 57 51" width="1292" src="https://user-images.githubusercontent.com/61280250/77487864-88df1280-6e6e-11ea-82db-1fe90769ae41.png">

thx!
BUT!
warning again!
installation of package ‘/tmp/RtmpMuHqzS/downloaded_packages/CRAN’ had non-zero exit status

**Comment by jukicivan** [comment]
I have the same issue.

**Comment by cvanderaa** [comment]
Hello, 
Sorry for the late response... This issue should be fixed by now! Please re-install the latest version of export using: 
```r
devtools::install_github("tomwenseleers/export")
```
