### ISSUE TITLE
graph2ppt() doesn't work1

### ISSUE THREAD

**Issue by realreal2020** [tomwenseleers/export#27]
Thanks for  Tomwenseleers job in R packages-export, it is so wonderful that I have spent several hours to install it.
however, once graph2ppt() was input where I wanted to save my plot generated by R, this bug would appear.

Error: 'ph_with_vg_at' is defunct.
Use 'officer::ph_with' instead.
See help("Defunct")

So I seek help here!
@tomwenseleers

**Comment by smouksassi** [comment]
there is a pending PR by the rvg author to fix this and related issue due to the deprecation of several functions form the officer ecosystem

**Comment by realreal2020** [comment]
> there is a pending PR by the rvg author to fix this and related issue due to the deprecation of several functions form the officer ecosystem

sorry to here that!
so all we have to do is wait?

**Comment by smouksassi** [comment]
You can fork , clone and merge the PR reinstall. Or you can  download the zip of the repo. Unzip, Replace the old files with the new as per the PR and re- install using devtools::install()

**Comment by realreal2020** [comment]
thxI have downloaded the repo zip. after unzipping, graph2office code was also be replaced by new code ph_with. Then, re-zip and local re-install with an old version 'rvg'. but, warning as"export.rdb corrupted". I was failed again…anyway, thank you so much for your kind-------- 原始邮件 --------发件人： Samer Mouksassi <notifications@github.com>日期： 2020年3月29日周日 半夜12:43收件人： tomwenseleers/export <export@noreply.github.com>抄送： realreal2020 <zjxvzhenzhen@126.com>, Author <author@noreply.github.com>主    题： Re: [tomwenseleers/export] graph2ppt() doesn't work1 (#27)
You can fork , clone and merge the PR reinstall. Or you can  download the zip of the repo. Unzip, Replace the old files with the new as per the PR and re- install using devtools::install()

**Comment by smouksassi** [comment]
There is a workflow for this explained here:
https://stackoverflow.com/questions/6022302/how-to-apply-unmerged-upstream-pull-requests-from-other-forks-into-my-fork

**Comment by cvanderaa** [comment]
Hello,
The PR has been merged ! Sorry for the delay... Export should work again after installing the newest version:
```r
devtools::install_github("tomwenseleers/export")
```
Let me know if issues persist.

**Comment by realreal2020** [comment]
Dear cvanderaa, thanks for your excellent work!-------- 原始邮件 --------发件人： cvanderaa <notifications@github.com>日期： 2020年4月2日周四 晚上10:06收件人： tomwenseleers/export <export@noreply.github.com>抄送： realreal2020 <zjxvzhenzhen@126.com>, Author <author@noreply.github.com>主    题： Re: [tomwenseleers/export] graph2ppt() doesn't work1 (#27)
Hello,
The PR has been merged ! Sorry for the delay... Export should work again after installing the newest version:
devtools::install_github("tomwenseleers/export")
Let me know if issues persist.

**Comment by cvanderaa** [comment]
Thank you for using our package! If you encounter a new issue, do not hesitate to open a new issue and tagging me in (@cvanderaa).
