### ISSUE TITLE
package ‘export’ is not available (for R version 4.0.2)

### ISSUE THREAD

**Issue by zhongshu98** [tomwenseleers/export#31]
Hello! I recently updated my R to 4.0.2version, however when I install the "export"package, R present with “package ‘export’ is not available (for R version 4.0.2)”.

**Comment by cvanderaa** [comment]
Indeed, we have had some deprecation issues that lead to the removal of `export` from CRAN... We have now fixed that issue are resubmitting the package to the archive. It will hopefully be back soon and I will keep you informed.

Meanwhile, you can reinstall `export` from Github using the following command:

```r
devtools::install_github("tomwenseleers/export)
```

**Comment by cvanderaa** [comment]
Actually I just realized that a new function we used got defunct. I'll come back to you once you can re-install the package!

**Comment by zhongshu98** [comment]
Thank you very much for such a rapid reply!

**Comment by cvanderaa** [comment]
So you can now reinstall the `export` package with the latest R version from this GitHub repo. We have submitted the package back to CRAN, hopefully it will be available there soon.

**Comment by zhongshu98** [comment]
> You can now (since commit [c832b74](https://github.com/tomwenseleers/export/commit/c832b74ce34c063c85015cb0c78bd47ecae4e2e2)) reinstall the `export` package with the latest R version from this GitHub repo. We have submitted the package back to CRAN, hopefully it will be available there soon.

Thank you very much! I have reinstalled the `export` package, and succeed!
