### ISSUE TITLE
graph2ppt error in an rshiny

### ISSUE THREAD

**Issue by lixiang117423** [tomwenseleers/export#38]
Hi Sir,
I am developing a Rshiny App with your package to export figures in **.pptx** format.
But the figure generated by _graph2ppt_ function has some error, the gap of world and number of the axis was filled by black color.
![01](https://user-images.githubusercontent.com/70553351/106755978-b5a4ae80-6669-11eb-931e-ec5019ce0801.png)
The function works well on Windows or Ubuntu, but it can not work correctly in an R shiny.
I do not know how to get the solution to the error. 
Any reply will be appreciated!
Thanks!

- [ ]

**Comment by cvanderaa** [comment]
Hello @lixiang117423,
Thank you for using our package! 

I'm not sure to understand what you are doing. Is this screenshot taken when you open the PPTX file that was created by your shiny app, or did you open and display the content of the PPTX from within the app?

It's the first time I see this issue, so I'm a bit clueless... Would have some example code for me to reproduce the issue? When exporting to a PPTX, we highly rely on the `officer` package. Depending on what you are doing, you might want to open an issue there.
