### ISSUE TITLE
issues about  graph2ppt

### ISSUE THREAD

**Issue by MMriran** [tomwenseleers/export#40]
Hi, thank you for you great tool！ It is very useful for us. However, I got a question about graph2ppt function. When I use graph2ppt, I found that I can not move all elements in my PPT， which means I can only move the title, axis, and figure legend and can not move the point in my figure. How can I solve it？

**Comment by MMriran** [comment]
May be there are too many elements in my plot，which  leads to the error？

**Comment by cvanderaa** [comment]
Hi @MMriran !

Thanks for you kind feedback!  Could you send a reproducible example or the PPT you obtain? It could be that some elements are automatically grouped when you open the PPT and need to be ungrouped (using `ctrl+shift+G` or so).

**Comment by MMriran** [comment]
> Hi @MMriran !
> 
> Thanks for you kind feedback! Could you send a reproducible example or the PPT you obtain? It could be that some elements are automatically grouped when you open the PPT and need to be ungrouped (using `ctrl+shift+G` or so).

Hi, thank you for your reply.  It more likely directly export a picture and some elements(picture can not ungrouped and elements can be ungrouped).  Can you leave a e-mali so that I can send the reproducible example or the PPT ？

**Comment by cvanderaa** [comment]
Sure, you can send to this address: `christophe.vanderaa` at `kuleuven.be`

**Comment by smouksassi** [comment]
you might want to ungroup the elements in ppt first
