### ISSUE TITLE
Graphics API version mismatch for R 4.1

### ISSUE THREAD

**Issue by felon02** [tomwenseleers/export#44]
I tried to export figures to ppt, i got error: Graphics API version mismatch
I searched and found a solution at stackOverFlow: https://stackoverflow.com/questions/68753250/getting-the-error-graphics-api-version-mismatch
however, I re-installed export, the question still exists.
below is my command the session info

> graph2ppt('test.pptx')
Error in PPTX_(file, bg, width, height, offx = offx, offy = offy, pointsize = pointsize,  : 
  Graphics API version mismatch
> R.version.string
[1] "R version 4.1.1 (2021-08-10)"

**Comment by sorenoneill** [comment]
> reinstalling `Cairo` didn't solve the problem. however, after reinstalling the whole packages that were necessary for export, the problem was solved. thank you a lot.

That is an ambiguous solution -- 'the whole packages' what does that entail?
