### ISSUE TITLE
library(export) crashing in R 4.2.0 

### ISSUE THREAD

**Issue by xjin15** [tomwenseleers/export#47]
After upgrading to R version 4.2.0, as long as the R package export is loaded, it will cause r to generate fatal errors

**Comment by cvanderaa** [comment]
Could you provide more information, such as the print of the fatal error? I am using R 4.2.0 and am not experiencing issues.

**Comment by tomwenseleers** [comment]
The only crashes that I ever experienced is when I try to export to a PPT file when I have that file simultaneously open in Powerpoint, which is maybe not surprising. In the absence of more details I'll close this issue for now...
