### ISSUE TITLE
Problem when editing the axis text after graph2pdf.

### ISSUE THREAD

**Issue by lincj1994** [tomwenseleers/export#48]
Hi.
I have created a plot using ggplot2 and exported it using graph2pdf. I wanted to edit it using illustrator and found a problem when editing the text of the x axis. Several of the texts were merged together and cannot be edited separately.  It seems the last number of each text is not in the right format.
I'm wondering if you can fix it.
Thanks.
Lin. 

![image](https://user-images.githubusercontent.com/60967283/180718582-bb1a40ea-ed81-44ef-a42e-e8e33d2c82d2.png)
![image](https://user-images.githubusercontent.com/60967283/180719336-ebd434bc-0370-4a50-bece-f780390d170b.png)

**Comment by cvanderaa** [comment]
Hello, 

Do you have the same issue with `export::graph2svg()`? 
I'm afraid there is not much we can do on our end. 

Note that you can do most of the axis editing with `ggplot2` directly.
