### ISSUE TITLE
Error in colformat_int

### ISSUE THREAD

**Issue by User1122334** [tomwenseleers/export#51]
Whatever I try, I am getting this error

`table2ppt(x=x,file=filen, digits = 1, digitspvals = 3)`

> Error in colformat_int(x = tab, col_keys = col.df) : 
>   unused argument (col_keys = col.df)

Even with the very basic example from the vignette run in an otherwise empty script I get this error. Am I doing something wrong here?

**Comment by cvanderaa** [comment]
Could you please provide the output of `sessionInfo()`. It is probably a version issue, either you are using an old version of some packages (hence updating packages should solve the issue), or you are using a new version and we have to fix this.

**Comment by tomwenseleers** [comment]
This should be resolved by updating these two packages on your side
`install.packages(c("officer", "flextable"))`
Closing this issue for now...
