### ISSUE TITLE
I can not install the export package.

### ISSUE THREAD

**Issue by ZChen90** [tomwenseleers/export#55]
I tried the following ways to install export, but neither of them worked:
1. 
install.packages("export")
library(export)

Error:
![image](https://github.com/tomwenseleers/export/assets/142398859/8bb6ac95-e5d2-40d5-be0c-4bef355c7a43)

2.
 install.packages("devtools")
library(devtools)
devtools::install_github("tomwenseleers/export", force = TRUE)
library(export)
RGL_USE_NULL = TRUE; options(rgl_useNULL = TRUE)
library(export)

Error:
![image](https://github.com/tomwenseleers/export/assets/142398859/e5c94425-c2c3-4951-b6c9-06322c56639e)

Could you please let me know how to install export package in this case? Thanks a lot!

**Comment by ZChen90** [comment]
I first tried 

install.packages("export")
install.packages("officer")
install.packages("rvg")
install.packages("openxlsx")
install.packages("ggplot2")
install.packages("flextable")
install.packages("xtable")
install.packages("rgl")
install.packages("stargazer")
install.packages("tikzDevice")
install.packages("xml2")
install.packages("broom")
install.packages("devtools")
devtools::install_github("tomwenseleers/export")
library(export)


the error was the same as above.

**Comment by tomwenseleers** [comment]
Can you try installing XQuartz first, from https://www.xquartz.org/ to see if that resolves the issue?
