### ISSUE TITLE
Error when trying to update

### ISSUE THREAD

**Issue by Mukei** [tomwenseleers/export#6]
Hi, I get the below error when trying to update the package with `devtools::install_github('tomwenseleers/export',local = F)`.

```
* installing *source* package ‘export’ ...
** R
** data
** inst
** preparing package for lazy loading
Warning: replacing previous import ‘ReporteRs::renderFlexTable’ by ‘rtable::renderFlexTable’ when loading ‘export’
Error : .onLoad failed in loadNamespace() for 'rgl', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Users/user.name/Library/R/3.3/library/rgl/libs/rgl.so':
  dlopen(/Users/user.name/Library/R/3.3/library/rgl/libs/rgl.so, 6): Library not loaded: /opt/X11/lib/libGLU.1.dylib
  Referenced from: /Users/user.name/Library/R/3.3/library/rgl/libs/rgl.so
  Reason: image not found
ERROR: lazy loading failed for package ‘export’
* removing ‘/Users/user.name/Library/R/3.3/library/export’
* restoring previous ‘/Users/user.name/Library/R/3.3/library/export’
Error: Command failed (1)
````

**Comment by tomwenseleers** [comment]
Hi Thomas,

I am also attaching the .ZIP file of the package - does that install OK by any chance?

Sounds like some problem that you have getting the rgl package installed, not sure where that issue is coming from...


cheers,

Tom


________________________________

**Comment by Mukei** [comment]
Hi Tom,

Thank you. I could install the package without trouble, but now I am getting various error

```
graph2ppt(file = paste0(today()," - filename.pptx"), aspectr = 1.7, fontname_sans = "Segoe UI", append = TRUE)
Error: lazy-load database '/Users/thomas.telandro/Library/R/3.3/library/export/R/export.rdb' is corrupt
In addition: Warning message:
internal error -3 in R_decompress1 
```

```
graph2ppt(file = paste0(today()," - filename.pptx"), aspectr = 1.7, append = TRUE)
Error: lazy-load database '/Users/thomas.telandro/Library/R/3.3/library/export/R/export.rdb' is corrupt
In addition: Warning messages:
1: restarting interrupted promise evaluation 
2: internal error -3 in R_decompress1 
```

Thanks,
Thomas

**Comment by Mukei** [comment]
After restarting my session and reloading the package I got the following error
```
Error : .onLoad failed in loadNamespace() for 'rgl', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Users/thomas.telandro/Library/R/3.3/library/rgl/libs/rgl.so':
  dlopen(/Users/thomas.telandro/Library/R/3.3/library/rgl/libs/rgl.so, 6): Library not loaded: /opt/X11/lib/libGLU.1.dylib
  Referenced from: /Users/thomas.telandro/Library/R/3.3/library/rgl/libs/rgl.so
  Reason: image not found
In addition: Warning message:
replacing previous import ‘ReporteRs::renderFlexTable’ by ‘rtable::renderFlexTable’ when loading ‘export’ 
Error: package or namespace load failed for ‘export’
```

**Comment by tomwenseleers** [comment]
Hi Thomas,

It sounds like you are having problems with the rgl library...

Can you install the rgl library OK, and does library(rgl) give you any errors then?


cheers,

Tom


________________________________

**Comment by Mukei** [comment]
Hi Tom,

I can install the library without trouble but when I try loading it I get:
```
Error : .onLoad failed in loadNamespace() for 'rgl', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Users/user.nameLibrary/R/3.3/library/rgl/libs/rgl.so':
  dlopen(/Users/user.nameLibrary/R/3.3/library/rgl/libs/rgl.so, 6): Library not loaded: /opt/X11/lib/libGLU.1.dylib
  Referenced from: /Users/user.name/Library/R/3.3/library/rgl/libs/rgl.so
  Reason: image not found
Error: package or namespace load failed for ‘rgl’
```

**Comment by tomwenseleers** [comment]
Hi Thomas,

This sounds more like something that should be addressed by the rgl package maintainers...

Are you working under Linux?

If so here is a thread that might be helpful:

https://github.com/bioconda/bioconda-recipes/issues/489


cheers,

Tom

**Comment by Mukei** [comment]
Tom, 
I am on OSX 10.11.6.
After install Quartz, all is working back again.
Only new (small) issue is that the font I was using is not found anymore (Segoe UI).

Thank you so much for your time and support!
Thomas

**Comment by tomwenseleers** [comment]
Hi Thomas,

I removed the argument font from my functions, but I think that specifying the font using

options("ReporteRs-default-font" = "Segoe UI")

or passing your font as option

fontname_sans = "Segoe UI" in graph2ppt may still work - have a try!

see ?addPlot in ReporteRs

(I believe at least that these options get passed on using the ... in my functions)


cheers,

Tom


________________________________
